// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package messaging

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockProducer creates a new instance of MockProducer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProducer(t interface {
	mock.TestingT
	Cleanup(func())
},
) *MockProducer {
	mock := &MockProducer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProducer is an autogenerated mock type for the Producer type
type MockProducer struct {
	mock.Mock
}

type MockProducer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProducer) EXPECT() *MockProducer_Expecter {
	return &MockProducer_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockProducer
func (_mock *MockProducer) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProducer_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockProducer_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockProducer_Expecter) Close() *MockProducer_Close_Call {
	return &MockProducer_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockProducer_Close_Call) Run(run func()) *MockProducer_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProducer_Close_Call) Return(err error) *MockProducer_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProducer_Close_Call) RunAndReturn(run func() error) *MockProducer_Close_Call {
	_c.Call.Return(run)
	return _c
}

// PublishUserEvent provides a mock function for the type MockProducer
func (_mock *MockProducer) PublishUserEvent(ctx context.Context, email string, otp string) error {
	ret := _mock.Called(ctx, email, otp)

	if len(ret) == 0 {
		panic("no return value specified for PublishUserEvent")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, email, otp)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProducer_PublishUserEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishUserEvent'
type MockProducer_PublishUserEvent_Call struct {
	*mock.Call
}

// PublishUserEvent is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - otp string
func (_e *MockProducer_Expecter) PublishUserEvent(ctx interface{}, email interface{}, otp interface{}) *MockProducer_PublishUserEvent_Call {
	return &MockProducer_PublishUserEvent_Call{Call: _e.mock.On("PublishUserEvent", ctx, email, otp)}
}

func (_c *MockProducer_PublishUserEvent_Call) Run(run func(ctx context.Context, email string, otp string)) *MockProducer_PublishUserEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockProducer_PublishUserEvent_Call) Return(err error) *MockProducer_PublishUserEvent_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProducer_PublishUserEvent_Call) RunAndReturn(run func(ctx context.Context, email string, otp string) error) *MockProducer_PublishUserEvent_Call {
	_c.Call.Return(run)
	return _c
}
